title: Biotech Game
description: "Pilot City Game"
owner_name: Kush Kharia
github_username: ThePencilSharpener
github_repo: "Biotech-Engagement-Game-Frontend" 
baseurl: "/biotech-game"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/legal&ethical.md
  - navigation/safecomputing.md